baseURL = 'https://konradwylde.github.io/'
languageCode = "en-us"
theme = "hello-friend-ng"
paginate     = 10
canonifyurls = true
hideHUGOSupport = false
enableRobotsTXT = true

[author]
  name = "Mr0x4b"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "SEO Consultant, Cybersecurity enthusiast, Ultra trail runner"
  enableThemeToggle = true
  disableReadOtherPosts = false
  enableSharingButtons = true

  # Metadata
  description = "Mr0x4b's blog on cyber threat intelligence and malware analysis. Explore expert insights, tips, and the latest updates to stay secure in the digital world."
  keywords = ""
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[params.footer]
    trademark = true
    rss = false
    copyright = true
    author = false
    topText = ['Mr0x4b']
    bottomText = ['']

[languages]
  [languages.en]
    title = "Mr0x4b"
    subtitle = "SEO Consultant, Cybersecurity enthusiast, Ultra trail runner"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd home"
      logoHomeLink = "/"
      logoMark= "> $"
      logoCursorColor = "#00FF00"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"


  # [[params.social]]
  #   name = "linkedin"
  #   url = "https://www.linkedin.com/in/profile/"

#  [[params.social]]
#    name = "github"
#    url = "https://github.com/mr0x4b"

  # [[params.social]]
  #   name = "instagram"
  #   url = "https://instagram.com/profile/"

  [[menu.main]]
    identifier = "threat-intelligence"
    name       = "Threat Intelligence"
    url        = "/threat-intelligence"
    weight     = 98

  [[menu.main]]
    identifier = "malware-analysis"
    name       = "Malware Analysis"
    url        = "/malware-analysis"
    weight     = 99

  # [[menu.main]]
  #   identifier = "blog"
  #   name       = "Blog"
  #   url        = "/posts"
  #   weight     = 100

[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"
